# [START runtime]
runtime: python
env: flex
entrypoint: gunicorn -b :$PORT cuttlet.wsgi

beta_settings:
    cloud_sql_instances: 'cuttlet-166523:us-west1:cuttlet-postgres'

runtime_config:
  python_version: 3
# [END runtime]

handlers:
- url: /.*
  secure: always
