# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-23 23:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
                ('account_type', models.TextField(default='')),
                ('thumbnail_url', models.TextField(default='defaultimgurl')),
                ('juice_ml', models.IntegerField(default=11)),
                ('all_juice', models.IntegerField(default=11)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
