# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuttlet_home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='all_juice',
            field=models.IntegerField(default=11),
        ),
        migrations.AlterField(
            model_name='profile',
            name='juice_ml',
            field=models.IntegerField(default=11),
        ),
    ]
