# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-06 23:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuttlet_home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='thumbnail_url',
            field=models.TextField(default='http://via.placeholder.com/36.png/8ADCE5?text=+'),
        ),
    ]
