# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-16 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuttlet_home', '0002_auto_20170706_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='all_juice',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='juice_ml',
            field=models.IntegerField(default=100),
        ),
    ]
