# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuttlet_home', '0002_auto_20170424_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='twitch_channel',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='youtube_channel',
            field=models.TextField(default=''),
        ),
    ]
