# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-01 04:27
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('supperfan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supperfanentry',
            name='id',
        ),
        migrations.AddField(
            model_name='supperfanentry',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
