# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-04 03:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supperfan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supperfanentry',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
