# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-01 04:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supperfan', '0002_auto_20170531_2327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supperfanentry',
            old_name='uuid',
            new_name='id',
        ),
    ]
