# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-01 04:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supperfan', '0003_auto_20170531_2329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supperfanentry',
            old_name='created_date',
            new_name='date_created',
        ),
    ]
